# Generated by Django 3.2.3 on 2022-06-24 04:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 6, 24, 4, 16, 50, 202399, tzinfo=utc)),
        ),
    ]
